FROM ubuntu:18.04

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
	unzip \
	wget

RUN wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip && \
	unzip ngrok-stable-linux-amd64.zip

COPY entrypoint-ngrok.sh /entrypoint-ngrok.sh