FROM python:3.6.4

RUN apt-get update && apt-get install -yqq xmlsec1

# Install dependencies
COPY requirements.txt /tmp/
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r /tmp/requirements.txt

COPY . /app/
WORKDIR /app