# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 01:51
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('parameters', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('status', models.CharField(max_length=32)),
                ('traceback', models.TextField(blank=True, null=True)),
                ('model_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ModelTemplate')),
            ],
        ),
    ]
