# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_modelrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelrun',
            name='output',
            field=models.TextField(blank=True, null=True),
        ),
    ]
