# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_modelrun_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelrun',
            name='output_zip',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
