# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 01:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170908_0122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelrun',
            old_name='parameters',
            new_name='inputs',
        ),
    ]
