# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 01:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170908_0126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modeltemplate',
            old_name='inputs',
            new_name='fields',
        ),
    ]
