# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170908_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelrun',
            name='output_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
