# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_modelrun_output_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelrun',
            name='backend',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='modelrun',
            name='ghap_ip',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='modelrun',
            name='ghap_username',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
