# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 00:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_modelrun_dataset'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelTemplate',
            new_name='AnalysisTemplate',
        ),
    ]
