# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20171004_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelrun',
            name='report_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
