# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-23 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_analysistemplate_needs_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelrun',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
