# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-23 01:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_modelrun_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelrun',
            name='model_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.AnalysisTemplate'),
        ),
    ]
