# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-13 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelrun',
            name='provision',
            field=models.TextField(blank=True, null=True),
        ),
    ]
