# Generated by Django 2.0.6 on 2018-10-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20180606_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelrun',
            name='base_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
