# Generated by Django 2.1.2 on 2018-10-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_modelrun_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelrun',
            name='postprocessing_attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelrun',
            name='postprocessing_traceback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
