# Generated by Django 2.1.2 on 2018-11-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_modelrun_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelrun',
            name='is_batch',
            field=models.BooleanField(default=False),
        ),
    ]
