# Generated by Django 2.1.2 on 2018-11-08 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_modelrun_is_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelrun',
            name='postprocessing_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
