# Generated by Django 2.1.2 on 2018-11-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_modelrun_postprocessing_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelrun',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
