#!/bin/bash
docker-compose run --entrypoint "bash -c" webapp "python manage.py flush --no-input"
docker-compose run --entrypoint "bash -c" webapp "python manage.py migrate"
docker-compose run --entrypoint "bash -c" webapp "python manage.py devseed"